import type { LegalEffect } from '@/types';

export const DEMO_LEGAL_EFFECTS: LegalEffect[] = [
  {
    "id": "eff-02-01-bkhdt",
    "category": "substantive_change",
    "effectType": "supplements",
    "sourceDocumentId": "doc-tt-02-2023-bkhdt",
    "sourceDocumentNumber": "02/2023/TT-BKHĐT",
    "sourceDocumentTitle": "Thông tư 02/2023/TT-BKHĐT sửa đổi, bổ sung Thông tư 01/2021/TT-BKHĐT",
    "targetDocumentId": "doc-tt-01-2021-bkhdt",
    "targetDocumentNumber": "01/2021/TT-BKHĐT",
    "targetProvisionId": "dieu-2",
    "targetProvisionLabel": "Điều 2. Hệ thống biểu mẫu sử dụng trong đăng ký doanh nghiệp, hộ kinh doanh",
    "clauseLabel": "Khoản 1",
    "pointLabel": "Điểm c",
    "effectiveFrom": "2023-07-01",
    "effectiveTo": null,
    "impactScope": "text_range",
    "legalCitation": "Khoản 2 Điều 1 Thông tư số 02/2023/TT-BKHĐT",
    "sourceProvisionCitation": "Khoản 2 Điều 1 Thông tư số 02/2023/TT-BKHĐT",
    "sourceExcerpt": "Sửa đổi, bổ sung các mẫu biểu tại Phụ lục III ban hành kèm theo Thông tư số 01/2021/TT-BKHĐT về đăng ký hộ kinh doanh điện tử.",
    "explanationSummary": "Nội dung này được sửa đổi, bổ sung bởi Thông tư 02/2023/TT-BKHĐT ban hành lại các mẫu biểu Phụ lục III cho hộ kinh doanh.",
    "sourceUrl": "https://thuvienphapluat.vn/van-ban/Doanh-nghiep/Thong-tu-02-2023-TT-BKHDT-sua-doi-Thong-tu-01-2021-TT-BKHDT-huong-dan-dang-ky-doanh-nghiep-564506.aspx",
    "anchor": {
      "id": "anc-02-01-bkhdt",
      "legalEffectId": "eff-02-01-bkhdt",
      "targetProvisionId": "dieu-2",
      "exactText": "Phụ lục III: Biểu mẫu sử dụng cho đăng ký hộ kinh doanh",
      "prefixText": "Ban hành kèm theo Thông tư này",
      "suffixText": "Phụ lục IV",
      "contentHash": "h_02_01_bkhdt",
      "resolutionStatus": "resolved"
    },
    "previousContent": "Sử dụng bộ biểu mẫu Phụ lục III ban hành kèm theo Thông tư 01/2021/TT-BKHĐT.",
    "replacementContent": "Sử dụng bộ biểu mẫu Phụ lục III sửa đổi ban hành kèm theo Thông tư 02/2023/TT-BKHĐT tích hợp đăng ký điện tử.",
    "reviewStatus": "verified",
    "confidence": 0.99
  },
  {
    "id": "eff-nd158-bhxh-k1",
    "category": "substantive_change",
    "effectType": "guides",
    "sourceDocumentId": "doc-nd-158-2025-nd-cp",
    "sourceDocumentNumber": "158/2025/NĐ-CP",
    "sourceDocumentTitle": "Nghị định 158/2025/NĐ-CP quy định chi tiết và hướng dẫn thi hành một số điều của Luật BHXH",
    "targetDocumentId": "doc-luat-41-2024-qh15",
    "targetDocumentNumber": "41/2024/QH15",
    "targetProvisionId": "dieu-2",
    "targetProvisionLabel": "Điều 2. Đối tượng tham gia bảo hiểm xã hội bắt buộc và tự nguyện",
    "clauseLabel": "Khoản 1",
    "effectiveFrom": "2025-07-01",
    "effectiveTo": null,
    "impactScope": "whole_provision",
    "legalCitation": "Khoản 1 Điều 2 Luật Bảo hiểm xã hội số 41/2024/QH15",
    "sourceProvisionCitation": "Điều 3 Nghị định số 158/2025/NĐ-CP",
    "sourceExcerpt": "Quy định chi tiết đối tượng tham gia bảo hiểm xã hội bắt buộc.",
    "explanationSummary": "Khoản 1 Điều này được hướng dẫn chi tiết bởi Nghị định 158/2025/NĐ-CP quy định về đối tượng tham gia BHXH.",
    "sourceUrl": "https://thuvienphapluat.vn/van-ban/Bao-hiem/Luat-Bao-hiem-xa-hoi-2024-41-2024-QH15.aspx",
    "anchor": {
      "id": "anc-nd158-bhxh-k1",
      "legalEffectId": "eff-nd158-bhxh-k1",
      "targetProvisionId": "dieu-2",
      "exactText": "1. Người lao động là công dân Việt Nam thuộc đối tượng tham gia bảo hiểm xã hội bắt buộc",
      "contentHash": "h_nd158_bhxh_k1",
      "resolutionStatus": "resolved"
    },
    "reviewStatus": "verified",
    "confidence": 0.99
  },
  {
    "id": "eff-nd158-bhxh-d1",
    "category": "substantive_change",
    "effectType": "guides",
    "sourceDocumentId": "doc-nd-158-2025-nd-cp",
    "sourceDocumentNumber": "158/2025/NĐ-CP",
    "sourceDocumentTitle": "Nghị định 158/2025/NĐ-CP quy định chi tiết và hướng dẫn thi hành một số điều của Luật BHXH",
    "targetDocumentId": "doc-luat-41-2024-qh15",
    "targetDocumentNumber": "41/2024/QH15",
    "targetProvisionLabel": "Điều 2. Đối tượng tham gia bảo hiểm xã hội bắt buộc và tự nguyện",
    "clauseLabel": "Khoản 1",
    "pointLabel": "Điểm d",
    "effectiveFrom": "2025-07-01",
    "effectiveTo": null,
    "impactScope": "whole_provision",
    "legalCitation": "Điểm d Khoản 1 Điều 2 Luật Bảo hiểm xã hội số 41/2024/QH15",
    "sourceProvisionCitation": "Khoản 2 Điều 4 Nghị định số 158/2025/NĐ-CP",
    "sourceExcerpt": "Quy định đối với người làm việc theo hợp đồng lao động không trọn thời gian.",
    "explanationSummary": "Điểm d Khoản 1 Điều này được hướng dẫn chi tiết bởi Nghị định 158/2025/NĐ-CP về điều kiện tham gia BHXH.",
    "sourceUrl": "https://thuvienphapluat.vn/van-ban/Bao-hiem/Luat-Bao-hiem-xa-hoi-2024-41-2024-QH15.aspx",
    "anchor": {
      "id": "anc-nd158-bhxh-d1",
      "legalEffectId": "eff-nd158-bhxh-d1",
      "targetProvisionId": "dieu-2",
      "exactText": "d) Người làm việc không trọn thời gian",
      "contentHash": "h_nd158_bhxh_d1",
      "resolutionStatus": "resolved"
    },
    "reviewStatus": "verified",
    "confidence": 0.99
  },
  {
    "id": "eff-nd20-nd132-gdlk",
    "category": "substantive_change",
    "effectType": "amends",
    "sourceDocumentId": "8ea00d09-efda-4832-aaf0-7b43e459b9c8",
    "sourceDocumentNumber": "20/2025/NĐ-CP",
    "sourceDocumentTitle": "Nghị định 20/2025/NĐ-CP sửa đổi, bổ sung một số điều của Nghị định 132/2020/NĐ-CP về giao dịch liên kết",
    "targetDocumentId": "27391d5a-3d79-40dd-a0bc-af04c2d8aed8",
    "targetDocumentNumber": "132/2020/NĐ-CP",
    "targetProvisionId": "dieu-5",
    "targetProvisionLabel": "Điều 5. Các bên có quan hệ liên kết",
    "clauseLabel": "Khoản 2",
    "pointLabel": "Điểm d",
    "effectiveFrom": "2025-03-27",
    "effectiveTo": null,
    "impactScope": "text_range",
    "legalCitation": "Khoản 1 Điều 1 Nghị định số 20/2025/NĐ-CP",
    "sourceProvisionCitation": "Khoản 1 Điều 1 Nghị định số 20/2025/NĐ-CP",
    "sourceExcerpt": "Loại trừ tổ chức tín dụng khỏi bên có quan hệ liên kết đối với các khoản vay thương mại thông thường nếu không trực tiếp hoặc gián tiếp điều hành doanh nghiệp.",
    "explanationSummary": "Nội dung này được sửa đổi bởi Nghị định 20/2025/NĐ-CP nhằm tháo gỡ vướng mắc trần lãi vay 30% EBITDA đối với các khoản vay ngân hàng.",
    "sourceUrl": "https://thuvienphapluat.vn/van-ban/Thue-Phi-Le-Phi/Nghi-dinh-20-2025-ND-CP-sua-doi-Nghi-dinh-132-2020-ND-CP-giao-dich-lien-ket.aspx",
    "anchor": {
      "id": "anc-nd20-nd132",
      "legalEffectId": "eff-nd20-nd132-gdlk",
      "targetProvisionId": "dieu-5",
      "exactText": "Một doanh nghiệp bảo lãnh hoặc cho một doanh nghiệp khác vay vốn",
      "prefixText": "Điều 5",
      "suffixText": "vốn góp của chủ sở hữu",
      "contentHash": "h_nd20_nd132",
      "resolutionStatus": "resolved"
    },
    "previousContent": "Tất cả các khoản vay ngân hàng đạt 25% vốn góp chủ sở hữu và 50% nợ trung dài hạn đều bị xác định là bên liên kết.",
    "replacementContent": "Loại trừ tổ chức tín dụng không tham gia điều hành, quản lý doanh nghiệp; điều chỉnh cách tính tổng dư nợ vay.",
    "reviewStatus": "verified",
    "confidence": 0.99
  },
  {
    "id": "eff-tt99-tt200",
    "category": "substantive_change",
    "effectType": "replaces",
    "sourceDocumentId": "53d8a6c0-91f3-44e9-a2fb-02197c03e814",
    "sourceDocumentNumber": "99/2025/TT-BTC",
    "sourceDocumentTitle": "Thông tư 99/2025/TT-BTC ban hành Chế độ kế toán doanh nghiệp",
    "targetDocumentId": "doc-tt-200-2014-tt-btc",
    "targetDocumentNumber": "200/2014/TT-BTC",
    "targetProvisionId": "dieu-130",
    "targetProvisionLabel": "Điều 130. Hiệu lực thi hành",
    "clauseLabel": "Toàn văn",
    "effectiveFrom": "2026-01-01",
    "effectiveTo": null,
    "impactScope": "whole_provision",
    "legalCitation": "Điều 120 Thông tư số 99/2025/TT-BTC",
    "sourceProvisionCitation": "Điều 120 Thông tư số 99/2025/TT-BTC",
    "sourceExcerpt": "Thông tư này thay thế toàn diện Thông tư số 200/2014/TT-BTC ngày 22/12/2014 của Bộ Tài chính từ ngày 01/01/2026.",
    "explanationSummary": "Thông tư 99/2025/TT-BTC thay thế toàn diện Thông tư 200/2014/TT-BTC để áp dụng Chế độ Kế toán Doanh nghiệp mới theo định hướng VFRS/IFRS.",
    "sourceUrl": "https://thuvienphapluat.vn/van-ban/Ke-toan-Kiem-toan/Thong-tu-99-2025-TT-BTC-che-do-ke-toan-doanh-nghiep.aspx",
    "anchor": {
      "id": "anc-tt99-tt200",
      "legalEffectId": "eff-tt99-tt200-bchkt",
      "targetProvisionId": "dieu-130",
      "exactText": "Thông tư này có hiệu lực thi hành từ ngày 01 tháng 01 năm 2015",
      "prefixText": "Điều 130",
      "suffixText": "thay thế Quyết định 15",
      "contentHash": "h_tt99_tt200",
      "resolutionStatus": "resolved"
    },
    "previousContent": "Áp dụng Chế độ kế toán doanh nghiệp theo Thông tư 200/2014/TT-BTC.",
    "reviewStatus": "verified",
    "confidence": 0.99
  }
];

export function getDocumentLegalEffects(docId: string): LegalEffect[] {
  return DEMO_LEGAL_EFFECTS.filter(
    (e) => e.targetDocumentId === docId || e.sourceDocumentId === docId
  );
}
