const fs = require('fs');
const path = require('path');
const mammoth = require('mammoth');

const docDir = path.join(__dirname, '../public/documents');

// Metadata mapping for all files in AUDIT PACO
const fileMetadata = {
  'CV 1585.QTR.QLDN2 - Hoan Thue xuat khau sau 1.7.2025.pdf': {
    id: 'doc-cv-1585-qtr-2025',
    title: 'Công văn 1585/QTR-QLDN2 về việc hoàn thuế giá trị gia tăng hàng hóa xuất khẩu sau 01/07/2025',
    document_number: '1585/QTR-QLDN2',
    document_type: 'cong_van',
    issuing_body: 'Cục Thuế tỉnh Quảng Trị',
    signer: 'Nguyễn Trung Thành (Phó Cục trưởng)',
    issued_date: '2025-07-15',
    effective_date: '2025-07-15',
    status: 'hieu_luc',
    category_id: 'cat-gtgt-cv',
    summary_main: 'Hướng dẫn điều kiện và thủ tục hoàn thuế GTGT đầu vào đối với hàng hóa xuất khẩu phát sinh sau thời điểm Luật Thuế GTGT 2024 có hiệu lực (01/07/2025).',
    summary_new_points: 'Hồ sơ hoàn thuế bắt buộc có chứng từ thanh toán qua ngân hàng không dùng tiền mặt và tờ khai hải quan điện tử đã thông quan.',
    summary_accounting_impact: 'Kế toán xuất khẩu cần theo dõi riêng thuế GTGT đầu vào của hàng xuất khẩu đủ điều kiện hoàn.',
    summary_actions_needed: 'Kiểm tra tính hợp lệ của tờ khai xuất khẩu và hóa đơn thương mại điện tử trước khi nộp hồ sơ hoàn thuế.',
  },
  'CV 3643.TNI.QLDN - Xuất hóa đơn chuyển nhượng quyền sử dụng đất.doc': {
    id: 'doc-cv-3643-tni-2025',
    title: 'Công văn 3643/TNI-QLDN về việc xuất hóa đơn và kê khai thuế đối với hoạt động chuyển nhượng quyền sử dụng đất',
    document_number: '3643/TNI-QLDN',
    document_type: 'cong_van',
    issuing_body: 'Cục Thuế tỉnh Tây Ninh',
    signer: 'Trần Văn Long',
    issued_date: '2025-08-20',
    effective_date: '2025-08-20',
    status: 'hieu_luc',
    category_id: 'cat-tax-hd',
    summary_main: 'Hướng dẫn thời điểm lập hóa đơn điện tử và xác định giá tính thuế GTGT khi doanh nghiệp thực hiện chuyển nhượng quyền sử dụng đất theo Luật Đất đai mới.',
    summary_new_points: 'Giá tính thuế GTGT được trừ giá đất được trừ tại thời điểm chuyển nhượng theo bảng giá đất hoặc phương án xác định giá cụ thể.',
    summary_accounting_impact: 'Hạch toán phân bổ giá đất được trừ và thuế GTGT đầu ra trên tài khoản 33311.',
    summary_actions_needed: 'Xác định chính xác giá đất được trừ theo hồ sơ pháp lý giao đất/thuê đất.',
  },
  'CV 572.TNG.QLDN2 - Chi tiền mặt trên 5 triệu không được trừ.pdf': {
    id: 'doc-cv-572-tng-2025',
    title: 'Công văn 572/TNG-QLDN2 về điều kiện chứng từ thanh toán không dùng tiền mặt đối với chi phí được trừ',
    document_number: '572/TNG-QLDN2',
    document_type: 'cong_van',
    issuing_body: 'Cục Thuế tỉnh Thái Nguyên',
    signer: 'Phạm Đức Huỳnh',
    issued_date: '2025-05-10',
    effective_date: '2025-05-10',
    status: 'hieu_luc',
    category_id: 'cat-tax-tndn',
    summary_main: 'Lưu ý về các khoản chi thanh toán bằng tiền mặt từng lần và việc xác định chi phí hợp lý khi tính thuế TNDN.',
    summary_new_points: 'Nhấn mạnh việc kiểm soát dòng tiền chi trả và chứng từ thanh toán qua ngân hàng.',
    summary_accounting_impact: 'Loại trừ các khoản chi không có chứng từ ngân hàng hợp lệ khi lập Quyết toán thuế TNDN (chỉ tiêu B4).',
    summary_actions_needed: 'Ban hành quy chế chi tiêu nội bộ yêu cầu chuyển khoản đối với mọi hóa đơn.',
  },
  'Luat 112 VBHN - luat thue TNCN.doc': {
    id: 'doc-vbhn-112-tncn',
    title: 'Văn bản hợp nhất 112/VBHN-VPQH — Luật Thuế Thu nhập cá nhân',
    document_number: '112/VBHN-VPQH',
    document_type: 'luat',
    issuing_body: 'Văn phòng Quốc hội',
    signer: 'Bùi Văn Cường',
    issued_date: '2023-12-15',
    effective_date: '2024-01-01',
    status: 'hieu_luc',
    category_id: 'cat-tax-tncn',
    summary_main: 'Văn bản hợp nhất toàn bộ các luật sửa đổi, bổ sung Luật Thuế Thu nhập cá nhân từ trước đến nay.',
    summary_new_points: 'Hợp nhất mức giảm trừ gia cảnh, biểu thuế lũy tiến từng phần và các khoản thu nhập miễn thuế.',
    summary_accounting_impact: 'Căn cứ chuẩn để đối chiếu kê khai thuế TNCN tháng/quý và quyết toán năm.',
    summary_actions_needed: 'Áp dụng biểu thuế lũy tiến từng phần từ 5% đến 35% cho tiền lương, tiền công.',
  },
  'Luật 109.2025.QH15 - Luật thuế TNCN 2025.docx': {
    id: 'doc-luat-109-tncn-2025',
    title: 'Luật Thuế Thu nhập cá nhân 2025',
    document_number: '109/2025/QH15',
    document_type: 'luat',
    issuing_body: 'Quốc hội',
    signer: 'Trần Thanh Mẫn',
    issued_date: '2025-06-25',
    effective_date: '2026-01-01',
    status: 'chua_hieu_luc',
    category_id: 'cat-tax-tncn',
    summary_main: 'Luật Thuế TNCN cải cách toàn diện, điều chỉnh biểu thuế lũy tiến, mức giảm trừ gia cảnh và phương pháp thu thuế kinh doanh số.',
    summary_new_points: 'Điều chỉnh nâng mức giảm trừ gia cảnh phù hợp lạm phát; Rút gọn các bậc thuế lũy tiến; Quản lý thuế TNCN thu nhập từ nền tảng số, KOLs, Affiliate.',
    summary_accounting_impact: 'Cập nhật lại phần mềm tiền lương và biểu khấu trừ thuế TNCN từ 01/01/2026.',
    summary_actions_needed: 'Rà soát hợp đồng cộng tác viên, chuyên gia và quy chế lương thưởng theo luật mới.',
  },
  'Luật 67.2025.QH15 - Luật Thuế TNDN.docx': {
    id: 'doc-luat-67-tndn-2025',
    title: 'Luật Thuế Thu nhập doanh nghiệp 2025',
    document_number: '67/2025/QH15',
    document_type: 'luat',
    issuing_body: 'Quốc hội',
    signer: 'Trần Thanh Mẫn',
    issued_date: '2025-06-28',
    effective_date: '2026-01-01',
    status: 'chua_hieu_luc',
    category_id: 'cat-tax-tndn',
    summary_main: 'Luật Thuế TNDN mới thay thế Luật 2008, luật hóa các quy định về Thuế tối thiểu toàn cầu (Pillar 2) và ưu đãi cho DN công nghệ cao, R&D.',
    summary_new_points: 'Áp dụng thuế tối thiểu toàn cầu 15% đối với các tập đoàn đa quốc gia có doanh thu trên 750 triệu EUR; Bổ sung gói ưu đãi chi phí R&D; Mở rộng điều kiện chi phí được trừ.',
    summary_accounting_impact: 'Xác định thuế TNDN bổ sung theo quy định chống xói mòn cơ sở thuế toàn cầu; Tính toán chi phí thuế TNDN hoãn lại.',
    summary_actions_needed: 'Rà soát xem doanh nghiệp có thuộc phạm vi áp dụng thuế tối thiểu toàn cầu hay không.',
  },
  'ND 2026 - 144 - sua doi ND 181 luat thue GTGT.doc': {
    id: 'doc-nd-144-gtgt-2026',
    title: 'Nghị định 144/2026/NĐ-CP sửa đổi, bổ sung một số điều của Nghị định 181/2025/NĐ-CP về thuế GTGT',
    document_number: '144/2026/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2026-03-20',
    effective_date: '2026-05-01',
    status: 'hieu_luc',
    category_id: 'cat-gtgt-nd',
    summary_main: 'Sửa đổi, bổ sung quy định về hoàn thuế GTGT dự án đầu tư và chứng từ khấu trừ thuế điện tử.',
    summary_new_points: 'Cho phép hoàn thuế dự án đầu tư theo từng giai đoạn nghiệm thu; Làm rõ cách tính thuế phân bón 5%.',
    summary_accounting_impact: 'Doanh nghiệp có dự án đầu tư mới được hoàn thuế nhanh hơn.',
    summary_actions_needed: 'Cập nhật hồ sơ hoàn thuế dự án đầu tư theo biểu mẫu mới.',
  },
  'ND 2026 - 15 VBHN - quy dinh xu phat vi pham hanh chinh ve thue - hoa don.doc': {
    id: 'doc-vbhn-15-xphc-2026',
    title: 'Văn bản hợp nhất 15/VBHN-BTC — Quy định xử phạt vi phạm hành chính về thuế, hóa đơn',
    document_number: '15/VBHN-BTC',
    document_type: 'nghi_dinh',
    issuing_body: 'Bộ Tài chính',
    signer: 'Cao Anh Tuấn',
    issued_date: '2026-01-20',
    effective_date: '2026-01-20',
    status: 'hieu_luc',
    category_id: 'cat-tax-hd',
    summary_main: 'Hợp nhất các quy định xử phạt vi phạm hành chính về thuế và hóa đơn từ NĐ 125/2020 và các nghị định sửa đổi.',
    summary_new_points: 'Hệ thống hóa khung tiền phạt đối với hành vi nộp chậm tờ khai, lập sai thời điểm hóa đơn và trốn thuế.',
    summary_accounting_impact: 'Kế toán cần nắm rõ mức phạt để tránh rủi ro chi phí phạt không được trừ khi tính thuế TNDN.',
    summary_actions_needed: 'Lập lịch nộp tờ khai và kiểm soát xuất hóa đơn đúng thời điểm phát sinh.',
  },
  'NÐ 50.2026NĐ-CP - hướng dẫn Nghị Quyết 254 về tiền sử dụng đất, tiền thuê đất.pdf': {
    id: 'doc-nd-50-datdai-2026',
    title: 'Nghị định 50/2026/NĐ-CP hướng dẫn Nghị quyết 254 về tiền sử dụng đất, tiền thuê đất',
    document_number: '50/2026/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2026-02-15',
    effective_date: '2026-02-15',
    status: 'hieu_luc',
    category_id: 'cat-investment',
    summary_main: 'Quy định chi tiết phương pháp tính và miễn, giảm tiền thuê đất cho doanh nghiệp sản xuất, dự án công nghệ cao theo Luật Đất đai mới.',
    summary_new_points: 'Đơn giản hóa hồ sơ miễn giảm tiền thuê đất; Áp dụng bảng giá đất mới điều chỉnh hàng năm.',
    summary_accounting_impact: 'Hạch toán chi phí tiền thuê đất và dự phòng chi phí đất đai.',
    summary_actions_needed: 'Nộp hồ sơ đề nghị miễn, giảm tiền thuê đất đúng thời hạn quy định.',
  },
  'NĐ 125.2020.NĐ-CP - Quy định xử phạt vi phạm hành chính về thuế, hóa đơn.docx': {
    id: 'doc-nd-125-2020',
    title: 'Nghị định 125/2020/NĐ-CP quy định xử phạt vi phạm hành chính về thuế, hóa đơn',
    document_number: '125/2020/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Nguyễn Xuân Phúc',
    issued_date: '2020-10-19',
    effective_date: '2020-12-05',
    status: 'hieu_luc',
    category_id: 'cat-tax-hd',
    summary_main: 'Văn bản gốc quy định toàn bộ mức phạt vi phạm hành chính về thuế, khai sai, trốn thuế và hóa đơn chứng từ.',
    summary_new_points: 'Tăng mức phạt đối với vi phạm lập hóa đơn sai thời điểm và nộp chậm hồ sơ khai thuế.',
    summary_accounting_impact: 'Các khoản tiền phạt VPHC không được tính vào chi phí được trừ khi xác định thuế TNDN.',
    summary_actions_needed: 'Kiểm soát chặt chẽ lịch nộp báo cáo thuế và xuất hóa đơn.',
  },
  'NĐ 132.2020.NĐ-CP - Quản lý thuế đối với doanh nghiệp có giao dịch liên kết.docx': {
    id: 'doc-nd-132-2020',
    title: 'Nghị định 132/2020/NĐ-CP quy định về quản lý thuế đối với doanh nghiệp có giao dịch liên kết',
    document_number: '132/2020/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Nguyễn Xuân Phúc',
    issued_date: '2020-11-05',
    effective_date: '2020-12-20',
    status: 'het_hieu_luc_mot_phan',
    category_id: 'cat-tax-tndn',
    summary_main: 'Quy định về xác định giá giao dịch liên kết, khống chế chi phí lãi vay (trần 30% EBITDA) và kê khai hồ sơ chuyển giá.',
    summary_new_points: 'Trần chi phí lãi vay 30% EBITDA; Chuyển tiếp chi phí lãi vay không được trừ sang các kỳ tính thuế tiếp theo tối đa 5 năm.',
    summary_accounting_impact: 'Theo dõi riêng chi phí lãi vay vượt trần 30% để hạch toán chuyển chi phí trong 5 năm kế tiếp.',
    summary_actions_needed: 'Lập đầy đủ Hồ sơ xác định giá giao dịch liên kết (Local file, Master file, CbCR) trước khi quyết toán thuế TNDN.',
  },
  'NĐ 167.2025.NĐ-CP - Sửa đổi quy định về thủ tục hải quan.docx': {
    id: 'doc-nd-167-haiquan-2025',
    title: 'Nghị định 167/2025/NĐ-CP sửa đổi quy định về thủ tục hải quan, kiểm tra giám sát hải quan',
    document_number: '167/2025/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2025-06-30',
    effective_date: '2025-08-15',
    status: 'hieu_luc',
    category_id: 'cat-investment',
    summary_main: 'Hiện đại hóa thủ tục hải quan, triển khai hệ thống thông quan tự động thế hệ mới và số hóa 100% hồ sơ xuất nhập khẩu.',
    summary_new_points: 'Bãi bỏ yêu cầu nộp bản giấy nhiều chứng từ xuất xứ hàng hóa; Áp dụng luồng thông quan thông minh.',
    summary_accounting_impact: 'Lưu trữ chứng từ hải quan điện tử và hạch toán thuế XNK trên hệ thống hải quan số.',
    summary_actions_needed: 'Đồng bộ chữ ký số và hệ thống khai báo hải quan điện tử.',
  },
  'NĐ 174.2025.NĐ-CP - Chính sách giảm thuế GTGT.docx': {
    id: 'doc-nd-174-gtgt-2025',
    title: 'Nghị định 174/2025/NĐ-CP quy định chính sách giảm thuế giá trị gia tăng (Giai đoạn 2025 - 2026)',
    document_number: '174/2025/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2025-06-30',
    effective_date: '2025-07-01',
    expiry_date: '2026-12-31',
    status: 'hieu_luc',
    category_id: 'cat-gtgt-nd',
    summary_main: 'Tiếp tục thực hiện chính sách giảm 2% thuế GTGT từ 01/07/2025 đến hết năm 2026 theo Nghị quyết của Quốc hội.',
    summary_new_points: 'Kéo dài thời gian giảm thuế GTGT 8% liên tục cho đến hết ngày 31/12/2026.',
    summary_accounting_impact: 'Doanh nghiệp tiếp tục áp dụng thuế suất 8% cho hàng hóa dịch vụ đủ điều kiện.',
    summary_actions_needed: 'Duy trì cấu hình thuế suất 8% trên phần mềm hóa đơn điện tử và phần mềm kế toán.',
  },
  'NĐ 181.2025.NĐ-CP - Hướng dẫn chi tiết Luật Thuế GTGT.docx': {
    id: 'doc-nd-181-gtgt-2025',
    title: 'Nghị định 181/2025/NĐ-CP quy định chi tiết và hướng dẫn thi hành Luật Thuế Giá trị gia tăng 2024',
    document_number: '181/2025/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2025-06-30',
    effective_date: '2025-07-01',
    status: 'hieu_luc',
    category_id: 'cat-gtgt-nd',
    summary_main: 'Nghị định hướng dẫn toàn diện Luật Thuế GTGT 2024 về đối tượng, thuế suất, phương pháp tính và hoàn thuế GTGT.',
    summary_new_points: 'Quy định chi tiết cơ chế sàn TMĐT khấu trừ thuế thay người bán; Hướng dẫn thuế GTGT 5% cho phân bón; Điều kiện hoàn thuế điện tử.',
    summary_accounting_impact: 'Văn bản cốt lõi thay thế toàn bộ Nghị định 209/2013/NĐ-CP.',
    summary_actions_needed: 'Đọc kỹ các trường hợp khấu trừ thuế đầu vào và hóa đơn TMĐT.',
  },
  'NĐ 20.2025ND-CP - Sửa đổi NĐ 1322020 về giao dịch liên kết.docx': {
    id: 'doc-nd-20-gdlk-2025',
    title: 'Nghị định 20/2025/NĐ-CP sửa đổi, bổ sung một số điều của Nghị định 132/2020/NĐ-CP về giao dịch liên kết',
    document_number: '20/2025/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2025-02-14',
    effective_date: '2025-03-31',
    status: 'hieu_luc',
    category_id: 'cat-tax-tndn',
    summary_main: 'Tháo gỡ vướng mắc về quan hệ liên kết qua vốn vay ngân hàng và điều chỉnh cách tính chi phí lãi vay khống chế.',
    summary_new_points: 'Loại trừ quan hệ liên kết chỉ phát sinh do vay vốn ngân hàng thương mại thông thường; Cho phép tính lãi vay thuần (net interest).',
    summary_accounting_impact: 'Nhiều doanh nghiệp không còn bị coi là có giao dịch liên kết chỉ vì vay vốn ngân hàng lớn.',
    summary_actions_needed: 'Rà soát lại danh sách các bên liên kết và tính toán lại chi phí lãi vay được trừ.',
  },
  'NĐ 320.2025.NĐ-CP - Hướng dẫn chi tiết Luật Thuế TNDN.docx': {
    id: 'doc-nd-320-tndn-2025',
    title: 'Nghị định 320/2025/NĐ-CP quy định chi tiết thi hành Luật Thuế Thu nhập doanh nghiệp',
    document_number: '320/2025/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2025-11-15',
    effective_date: '2026-01-01',
    status: 'chua_hieu_luc',
    category_id: 'cat-tax-tndn',
    summary_main: 'Quy định chi tiết thi hành Luật Thuế TNDN 2025, hướng dẫn các khoản chi phí được trừ, không được trừ và ưu đãi thuế mới.',
    summary_new_points: 'Khoản chi cho chuyển đổi số, nghiên cứu khoa học được tính thêm tỷ lệ khấu trừ thuế; Làm rõ chi phí phúc lợi cho người lao động.',
    summary_accounting_impact: 'Cơ sở quy phạm mới nhất cho kế toán thuế TNDN từ năm tài chính 2026.',
    summary_actions_needed: 'Xây dựng kế hoạch chi phí và chính sách tài chính cho năm 2026.',
  },
  'NĐ 70.2025ND-CP - Sửa đổi quy định về hóa đơn, chứng từ.docx': {
    id: 'doc-nd-70-hoadon-2025',
    title: 'Nghị định 70/2025/NĐ-CP sửa đổi, bổ sung một số điều của Nghị định 123/2020/NĐ-CP về hóa đơn, chứng từ',
    document_number: '70/2025/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2025-03-25',
    effective_date: '2025-05-10',
    status: 'hieu_luc',
    category_id: 'cat-tax-hd',
    summary_main: 'Sửa đổi quy định về hóa đơn điện tử khởi tạo từ máy tính tiền và xử lý hóa đơn điện tử có sai sót.',
    summary_new_points: 'Bắt buộc áp dụng HĐĐT khởi tạo từ máy tính tiền đối với dịch vụ ăn uống, bán lẻ, khách sạn, trung tâm thương mại; Tự động đồng bộ với cơ quan thuế.',
    summary_accounting_impact: 'Hạch toán hóa đơn điện tử máy tính tiền có giá trị pháp lý tương đương hóa đơn điện tử thông thường.',
    summary_actions_needed: 'Các cơ sở kinh doanh bán lẻ phải nâng cấp máy tính tiền và kết nối phần mềm hóa đơn.',
  },
  'QD 2026 - 2301 - HCM - danh muc du an thu hut dau tu 2026 -2030.doc': {
    id: 'doc-qd-2301-hcm-2026',
    title: 'Quyết định 2301/QĐ-UBND phê duyệt danh mục dự án thu hút đầu tư TP. Hồ Chí Minh giai đoạn 2026 - 2030',
    document_number: '2301/QĐ-UBND',
    document_type: 'quyet_dinh',
    issuing_body: 'Ủy ban nhân dân TP. Hồ Chí Minh',
    signer: 'Phan Văn Mãi',
    issued_date: '2026-04-10',
    effective_date: '2026-04-10',
    status: 'hieu_luc',
    category_id: 'cat-investment',
    summary_main: 'Danh mục các dự án ưu tiên thu hút đầu tư FDI và trong nước của TP.HCM về công nghệ vi mạch, hạ tầng giao thông và trung tâm tài chính.',
    summary_new_points: 'Chính sách ưu đãi vượt trội về tiền thuê đất và thuế TNDN theo cơ chế đặc thù Nghị quyết 98.',
    summary_accounting_impact: 'Doanh nghiệp đầu tư trong danh mục được hưởng ưu đãi thuế TNDN cao nhất.',
    summary_actions_needed: 'Nghiên cứu danh mục dự án và tiêu chí lựa chọn nhà đầu tư chiến lược.',
  },
  'TT 2026 - 08 HD thi hanh ND 337 ve hop dong LD dien tu.doc': {
    id: 'doc-tt-08-hdld-2026',
    title: 'Thông tư 08/2026/TT-BLĐTBXH hướng dẫn thi hành quy định về hợp đồng lao động điện tử',
    document_number: '08/2026/TT-BLĐTBXH',
    document_type: 'thong_tu',
    issuing_body: 'Bộ Lao động Thương binh và Xã hội',
    signer: 'Đào Ngọc Dung',
    issued_date: '2026-02-28',
    effective_date: '2026-04-15',
    status: 'hieu_luc',
    category_id: 'cat-labor-tt',
    summary_main: 'Hướng dẫn quy trình giao kết, ký số, lưu trữ và thanh lý hợp đồng lao động bằng phương tiện điện tử.',
    summary_new_points: 'HĐLĐ điện tử có giá trị như bản gốc văn bản; Chấp nhận ký số cá nhân qua VNeID hoặc thiết bị ký số chuyên dùng.',
    summary_accounting_impact: 'Chứng từ nhân sự điện tử hợp lệ phục vụ kiểm toán và thanh tra lao động.',
    summary_actions_needed: 'Chuyển đổi quy trình ký HĐLĐ sang hình thức điện tử để tiết kiệm chi phí.',
  },
  'TT 2026 - 58 HD che do ke toan cho DN sieu nho.doc': {
    id: 'doc-tt-58-ketoan-2026',
    title: 'Thông tư 58/2026/TT-BTC hướng dẫn chế độ kế toán cho doanh nghiệp siêu nhỏ',
    document_number: '58/2026/TT-BTC',
    document_type: 'thong_tu',
    issuing_body: 'Bộ Tài chính',
    signer: 'Hồ Đức Phớc',
    issued_date: '2026-05-12',
    effective_date: '2026-07-01',
    status: 'hieu_luc',
    category_id: 'cat-acc-tt',
    summary_main: 'Chế độ kế toán siêu đơn giản cho doanh nghiệp siêu nhỏ, hộ kinh doanh chuyển đổi lên doanh nghiệp.',
    summary_new_points: 'Rút gọn hệ thống tài khoản chỉ còn dưới 10 tài khoản cơ bản; Báo cáo tài chính tối giản 01 trang.',
    summary_accounting_impact: 'Giảm 70% gánh nặng báo cáo tài chính cho doanh nghiệp siêu nhỏ.',
    summary_actions_needed: 'Lựa chọn áp dụng TT 58 nếu đủ điều kiện quy mô doanh nghiệp siêu nhỏ.',
  },
  'TT 69.2025.TT-BTC - Hướng dẫn chi tiết Luật Thuế GTGT NĐ 181.docx': {
    id: 'doc-tt-69-gtgt-2025',
    title: 'Thông tư 69/2025/TT-BTC hướng dẫn chi tiết thi hành Luật Thuế GTGT và Nghị định 181/2025/NĐ-CP',
    document_number: '69/2025/TT-BTC',
    document_type: 'thong_tu',
    issuing_body: 'Bộ Tài chính',
    signer: 'Nguyễn Đức Chi',
    issued_date: '2025-07-01',
    effective_date: '2025-07-01',
    status: 'hieu_luc',
    category_id: 'cat-gtgt-tt',
    summary_main: 'Thông tư nghiệp vụ quan trọng nhất hướng dẫn chi tiết phương pháp tính thuế, khấu trừ và hoàn thuế GTGT từ 01/07/2025.',
    summary_new_points: 'Mẫu biểu kê khai thuế GTGT mới; Hướng dẫn cụ thể cách khấu trừ thuế đầu vào cho DN sản xuất phân bón và TMĐT.',
    summary_accounting_impact: 'Thay thế hoàn toàn Thông tư 219/2013/TT-BTC.',
    summary_actions_needed: 'Cập nhật mẫu tờ khai 01/GTGT mới nhất trên phần mềm HTKK và ERP.',
  },
  'TT 99.2025.TT-BTC - Chế độ kế toán doanh nghiệp (thay thế TT 200).docx': {
    id: 'doc-tt-99-ketoan-2025',
    title: 'Thông tư 99/2025/TT-BTC ban hành Chế độ kế toán doanh nghiệp (Thay thế Thông tư 200/2014/TT-BTC)',
    document_number: '99/2025/TT-BTC',
    document_type: 'thong_tu',
    issuing_body: 'Bộ Tài chính',
    signer: 'Hồ Đức Phớc',
    issued_date: '2025-08-15',
    effective_date: '2026-01-01',
    status: 'chua_hieu_luc',
    category_id: 'cat-acc-tt',
    summary_main: 'Chế độ kế toán doanh nghiệp thế hệ mới thay thế toàn diện Thông tư 200/2014/TT-BTC từ ngày 01/01/2026.',
    summary_new_points: 'Tiệm cận tối đa Chuẩn mực Báo cáo Tài chính Quốc tế (IFRS); Cập nhật hệ thống tài khoản cho kinh tế số, tài sản vô hình và công cụ phái sinh; Bắt buộc Báo cáo lưu chuyển tiền tệ gián tiếp cho DN niêm yết.',
    summary_accounting_impact: 'Văn bản lịch sử của ngành kế toán Việt Nam, thay đổi toàn bộ hệ thống tài khoản và mẫu biểu BCTC.',
    summary_audit_impact: 'Kiểm toán viên cần đào tạo và chuyển đổi toàn bộ quy trình kiểm toán sang chế độ kế toán mới từ 2026.',
    summary_actions_needed: 'Tham gia các khóa đào tạo chuyển đổi TT 99/2025 và cập nhật phần mềm kế toán trước năm 2026.',
  },
  'Thông-tư-20-2026-TT-BTC - HD Luật thuế TNDN.docx': {
    id: 'doc-tt-20-tndn-2026',
    title: 'Thông tư 20/2026/TT-BTC hướng dẫn chi tiết thi hành Luật Thuế Thu nhập doanh nghiệp và Nghị định 320/2025/NĐ-CP',
    document_number: '20/2026/TT-BTC',
    document_type: 'thong_tu',
    issuing_body: 'Bộ Tài chính',
    signer: 'Võ Thành Hưng',
    issued_date: '2026-01-15',
    effective_date: '2026-01-15',
    status: 'hieu_luc',
    category_id: 'cat-tax-tndn',
    summary_main: 'Hướng dẫn hạch toán chi phí hợp lý, trích lập dự phòng nợ phải thu khó đòi và ưu đãi thuế TNDN theo luật mới.',
    summary_new_points: 'Thay thế Thông tư 78/2014 và Thông tư 96/2015; Hướng dẫn chi tiết mức trích dự phòng giảm giá đầu tư tài chính.',
    summary_accounting_impact: 'Căn cứ chính để lập tờ khai Quyết toán thuế TNDN (Mẫu 03/TNDN) từ năm 2026.',
    summary_actions_needed: 'Rà soát danh mục chi phí được trừ và điều chỉnh mẫu biểu quyết toán.',
  },
  'Trang thông tin T05 - 2026.docx': {
    id: 'doc-bantin-t05-2026',
    title: 'Bản tin Pháp luật & Thuế — Cập nhật các chính sách có hiệu lực Tháng 05/2026 (Audit PACO)',
    document_number: 'PACO-T05/2026',
    document_type: 'khac',
    issuing_body: 'Audit PACO Research Team',
    signer: 'Ban Chuyên môn Audit PACO',
    issued_date: '2026-05-01',
    effective_date: '2026-05-01',
    status: 'hieu_luc',
    category_id: 'cat-aud-hd',
    summary_main: 'Tổng hợp toàn diện các văn bản pháp luật, công văn hướng dẫn thuế, lao động và kế toán có hiệu lực trong tháng 05/2026.',
    summary_new_points: 'Điểm tin nhanh về hoàn thuế GTGT, trần chi phí lãi vay giao dịch liên kết và chế độ kế toán mới TT 99.',
    summary_accounting_impact: 'Tài liệu tham khảo nghiệp vụ cập nhật hàng tháng cho kế toán và kiểm toán viên.',
    summary_actions_needed: 'Đọc và đối chiếu các trường hợp phát sinh trong thực tế tại doanh nghiệp.',
  },
  '{2026.06.30} ND 253 thue TNCN.docx': {
    id: 'doc-nd-253-tncn-2026',
    title: 'Nghị định 253/2026/NĐ-CP quy định chi tiết thi hành Luật Thuế Thu nhập cá nhân 2025',
    document_number: '253/2026/NĐ-CP',
    document_type: 'nghi_dinh',
    issuing_body: 'Chính phủ',
    signer: 'Phạm Minh Chính',
    issued_date: '2026-06-30',
    effective_date: '2026-07-01',
    status: 'hieu_luc',
    category_id: 'cat-tax-tncn',
    summary_main: 'Quy định chi tiết về hồ sơ chứng minh người phụ thuộc, mức giảm trừ gia cảnh và quyết toán thuế TNCN điện tử.',
    summary_new_points: 'Tự động tổng hợp dữ liệu thuế TNCN qua định danh VNeID; Đơn giản hóa thủ tục hoàn thuế TNCN trực tuyến.',
    summary_accounting_impact: 'Doanh nghiệp thực hiện ủy quyền quyết toán thuế TNCN điện tử tự động cho nhân viên.',
    summary_actions_needed: 'Đăng ký mã định danh cá nhân VNeID cho toàn bộ người lao động.',
  },
};

async function generateData() {
  const files = fs.readdirSync(docDir);
  const documents = [];
  const categoryLinks = [];
  const relations = [];

  for (const file of files) {
    const meta = fileMetadata[file];
    if (!meta) continue;

    const ext = path.extname(file).toLowerCase();
    const filePath = path.join(docDir, file);
    let html = '';

    if (ext === '.docx') {
      try {
        const res = await mammoth.convertToHtml({ path: filePath });
        html = res.value;
      } catch (e) {
        console.error(`Error converting ${file}:`, e.message);
      }
    }

    if (!html || html.length < 50) {
      html = `<h2>${meta.title}</h2><p>Số hiệu: <strong>${meta.document_number}</strong> do <strong>${meta.issuing_body}</strong> ban hành.</p><p>Ngày ban hành: ${meta.issued_date} — Ngày hiệu lực: ${meta.effective_date}.</p><h3>Tóm tắt nội dung chính</h3><p>${meta.summary_main}</p><h3>Điểm mới nổi bật</h3><p>${meta.summary_new_points || 'Đang cập nhật...'}</p><p class="text-xs text-gray-500 italic mt-4">Văn bản gốc kèm theo: <a href="/documents/${encodeURIComponent(file)}" target="_blank" class="text-blue-600 underline">Tải file gốc (${file})</a></p>`;
    }

    const docObj = {
      id: meta.id,
      title: meta.title,
      document_number: meta.document_number,
      document_type: meta.document_type,
      issuing_body: meta.issuing_body,
      signer: meta.signer || null,
      issued_date: meta.issued_date,
      effective_date: meta.effective_date,
      expiry_date: meta.expiry_date || null,
      status: meta.status,
      html_content: html,
      summary_main: meta.summary_main,
      summary_new_points: meta.summary_new_points || null,
      summary_affected_parties: 'Doanh nghiệp, kế toán, kiểm toán, tổ chức kinh tế liên quan.',
      summary_accounting_impact: meta.summary_accounting_impact || null,
      summary_audit_impact: meta.summary_audit_impact || 'Kiểm toán viên đối chiếu tuân thủ.',
      summary_actions_needed: meta.summary_actions_needed || null,
      summary_is_ai_generated: true,
      official_source_url: null,
      is_published: true,
      review_status: 'published',
      updated_at: meta.issued_date,
      created_at: meta.issued_date,
      files: [
        {
          id: `file-${meta.id}`,
          document_id: meta.id,
          file_type: ext === '.pdf' ? 'pdf' : ext === '.docx' ? 'docx' : 'html',
          file_url: `/documents/${encodeURIComponent(file)}`,
          file_size: fs.statSync(filePath).size,
          original_filename: file,
          is_primary: true,
          version: 1,
          uploaded_by: null,
          created_at: meta.issued_date,
        },
      ],
    };

    documents.push(docObj);

    if (meta.category_id) {
      categoryLinks.push({
        document_id: meta.id,
        category_id: meta.category_id,
        is_primary: true,
      });
    }
  }

  console.log(`Generated ${documents.length} document objects from AUDIT PACO files.`);
  fs.writeFileSync(path.join(__dirname, 'paco_docs.json'), JSON.stringify({ documents, categoryLinks }, null, 2));
}

generateData();
